sudo: true
notifications:
  email: false
language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: linux
      before_install:
        - export CC=`which clang`
        - export CXX=`which clang++`
        - sudo ln -s `which clang++` /usr/bin/clang++
        - sudo ln -s `which clang` /usr/bin/clang
        - sudo ln -s `which node` /usr/bin/node
        - sudo ln -s `which npm` /usr/bin/npm
    # - os: osx
    
    
# install: npm install -g

# before_script: cd tests/J2C/SYNC

script:
  - npm install tiny-worker
  - npm run link
# put testing scripts here
  - jamrun tests/J2C/SYNC/j2ctest_test.jxe
